In [4]:
#EXERCICIO 1
valorEmprestimo = float(input('Introduza o valor do empréstimo: '))
salario = float(input('Introduza o salário do comprador: '))
anos = int(input('Introduza a quantidade de anos a creditar: '))

qtdMeses = anos * 12
valorPrestacao = valorEmprestimo / qtdMeses

if (valorPrestacao < (salario * 0.3)):
    print(f'O crédito foi aprovado. O valor da prestação é {valorPrestacao} durante {anos} anos.')
else:
    print('O crédito foi recusado.')

Introduza o valor do empréstimo:  150000
Introduza o salário do comprador:  1500
Introduza a quantidade de anos a creditar:  40


O crédito foi aprovado. O valor da prestação é 312.5 durante 40 anos.


In [14]:
#EXERCICIO 2
precoCompra = float(input('Introduza o valor da compra: '))
metodoPagamento = int(input('Introduza o método de pagamento: 1 - Pronto pagamento ou 2 - Parcelado'))

if metodoPagamento == 2:
    qtdPagamentos = int(input('Introduza quantos pagamentos pretende fazer'))
    if qtdPagamentos <= 1:
        print('Introduziu um valor inválido')
    else: 
        print(f'Valor inicial: {precoCompra}')
    
    if qtdPagamentos == 2:
        print ('O preco não sofreu alterações')
    elif qtdPagamentos == 3:
        print ('O preco aumentou 20% com os juros')
        precoCompra = precoCompra * 1.2
elif metodoPagamento == 1:
    print ('Teve desconto de 10%')
    precoCompra = precoCompra * 0.9
else:
    print ('Introduziu um método errado')
    exit

print(f'O valor final é {precoCompra}')



Introduza o valor da compra:  150000
Introduza o método de pagamento: 1 - Pronto pagamento ou 2 - Parcelado 1


Teve desconto de 10%
O valor final é 135000.0


In [13]:
#EXERCICIO 3
import random
possibilidades = ['Pedra', 'Papel', 'Tesoura']
vitorias = 0
jogos = 10
for i in range (jogos):
    print('Jogo nº', i+1)
    jogada = input('Qual é a sua jogada?')

    while jogada not in possibilidades:
        jogada = int(input('Entrada inválida! Qual é a sua jogada?'))

    computador = random.choice(possibilidades)
    print('O computador jogou ', computador)

    if jogada == computador:
        print('Empate!')
    elif ( (jogada == 'Pedra' and computador == 'Tesoura') or
           (jogada == 'Papel' and computador == 'Pedra') or
           (jogada == 'Tesoura' and computador == 'Papel') ):
        print('Ganhaste!')
        vitorias+=1
    else:
        print('Perdeste!')

percentagem = vitorias / jogos * 100
print('Ganhaste ', percentagem, '% dos jogos')


Jogo nº 1


Qual é a sua jogada? Pedra


O computador jogou  Tesoura
Ganhaste!
Jogo nº 2


Qual é a sua jogada? Pedra


O computador jogou  Papel
Perdeste!
Jogo nº 3


Qual é a sua jogada? Pedra


O computador jogou  Papel
Perdeste!
Jogo nº 4


Qual é a sua jogada? Pedra


O computador jogou  Pedra
Empate!
Jogo nº 5


Qual é a sua jogada? Pedra


O computador jogou  Pedra
Empate!
Jogo nº 6


Qual é a sua jogada? Pedra


O computador jogou  Pedra
Empate!
Jogo nº 7


Qual é a sua jogada? Pedra


O computador jogou  Pedra
Empate!
Jogo nº 8


Qual é a sua jogada? Pedra


O computador jogou  Tesoura
Ganhaste!
Jogo nº 9


Qual é a sua jogada? Pedra


O computador jogou  Papel
Perdeste!
Jogo nº 10


Qual é a sua jogada? Pedra


O computador jogou  Papel
Perdeste!
Ganhaste  20.0 % dos jogos


In [10]:
#EXERCICIO 4
lista = []
a = True
while a == True:
    valor = int(input('Introduza um valor positivo: '))
    if valor == 0:
        print ('Introduziu um valor inválido')
    if valor > 0:
        if valor in lista:
            print('Introduziu um valor repetido')
        else:
            if len(lista) == 0:
                menor = valor
                maior = valor
            elif valor > maior:
                maior = valor
            elif valor < menor:
                menos = valor
            lista.append(valor)
    elif valor < 0:
        a = False
        print('Introduziu um valor negativo')
        for c,v in enumerate(lista):
            print(f'Na posição {c} encontrei o valor {v}')
        print(f'O maior é {maior} e o menor é {menor}')

Introduza um valor positivo:  5
Introduza um valor positivo:  3
Introduza um valor positivo:  1
Introduza um valor positivo:  10
Introduza um valor positivo:  0


Introduziu um valor inválido


Introduza um valor positivo:  -2


Introduziu um valor negativo
Na posição 0 encontrei o valor 5
Na posição 1 encontrei o valor 3
Na posição 2 encontrei o valor 1
Na posição 3 encontrei o valor 10
O maior é 10 e o menor é 5


In [15]:
# EXERCICIO 5
lista = []
for i in range (5):
    valor = int(input('Introduza o valor numérico'))
    lista.append(valor)

for x in range(len(lista) - 1):
    if lista[x] > lista[x+1]:
        helper = lista[x+1]
        lista[x+1] = lista[x]
        lista [x] = helper
        
print(lista)



Introduza o valor numérico 2
Introduza o valor numérico 1
Introduza o valor numérico 4
Introduza o valor numérico 3
Introduza o valor numérico 5


[1, 2, 3, 4, 5]


In [ ]:
# EXERCICIO 6
lista = []
qtdValores=10

for i in range (qtdValores):
    valor = int(input('Introduza o valor: '))
    if (valor%2 == 0):
        for i in range(5):
            if (valor  lista[i]):
        
            
    lista.append(valor)
    

In [34]:
# EXERCICIO 7
import numpy as np

qtdLinhas = int(input('Quantas linhas queres que a matriz tenha?'))
qtdNumeros = qtdLinhas * qtdLinhas
lista = np.zeros((qtdLinhas, qtdLinhas));
somaPares = 0
somaRdColuna = 0
menor = 0
numeroNovo = 0

for x in range(qtdLinhas):
    for y in range(qtdLinhas):
        ms = f'Introduza o número: {(x,y)}'
        numero = int(input(ms))

        lista[x, y] = numero

        if (numero%2 == 0):
            somaPares += numero

        if (y == 2):
            somaRdColuna += numero

for y in range(qtdLinhas):
    if (y==0):
        menor = lista [1, y]
    else:
        numeroNovo = lista [1, y]
        if (numeroNovo < menor):
            menor = numeroNovo
    
print(lista)
print(f'A soma dos numeros pares é: {somaPares}')
print(f'A soma da terceira coluna é: {somaRdColuna}')
print(f'O menor valor da segunda linha é: {menor}')




Quantas linhas queres que a matriz tenha? 3
Introduza o número: (0, 0) 1
Introduza o número: (0, 1) 2
Introduza o número: (0, 2) 3
Introduza o número: (1, 0) 4
Introduza o número: (1, 1) 5
Introduza o número: (1, 2) 6
Introduza o número: (2, 0) 7
Introduza o número: (2, 1) 8
Introduza o número: (2, 2) 9


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
A soma dos numeros pares é: 20
A soma da terceira coluna é: 18
O menor valor da segunda linha é: 4.0


In [4]:
# EXERCICIO 8

lista = [['Número', 'Nome', 'Média']]

while True:
    numero = int(input('Introduza o seu número de aluno: '))
    nome = input('Introduza o seu nome: ')
    nota1 = int(input('Introduza a primeira nota: '))
    nota2 = int(input('Introduza a segunda nota: '))
    media = (nota1 + nota2)/2

    lista.append([numero, nome, media])

    continuar = input("Quer continuar? [S/N]: ").upper()
    if continuar == 'N':
        break

print("\n{:<10} {:<20} {:<10}".format("Número", "Nome", "Média"))
print("-" * 42)

for aluno in lista[1:]:
    print("{:<10} {:<20} {:<10.2f}".format(aluno[0], aluno[1], aluno[2]))

Introduza o seu número de aluno:  123
Introduza o seu nome:  nuno
Introduza a primeira nota:  1
Introduza a segunda nota:  3
Quer continuar? [S/N]:  s
Introduza o seu número de aluno:  321
Introduza o seu nome:  rod
Introduza a primeira nota:  3
Introduza a segunda nota:  1
Quer continuar? [S/N]:  n



Número     Nome                 Média     
------------------------------------------
123        nuno                 2.00      
321        rod                  2.00      


In [13]:
# EXERCICIO 9

def contador(inicio, fim, passo):
    if inicio < fim:
        while inicio <= fim:
            print(inicio, end=" ")
            inicio += passo
    else:
        while inicio >= fim:
            print(inicio, end=" ")
            inicio -= passo

    print("\n")


# 1ª contagem
contador(1, 10, 1)

# 2ª contagem
contador(10, 0, 2)

start = int(input('Introduza o inicio: '))
end = int(input('Introduza o final: '))
passe = int(input('Introduza o passo personalizado: '))

contador(start, end, passe)

    



1 2 3 4 5 6 7 8 9 10 

10 8 6 4 2 0 



Introduza o inicio:  1
Introduza o final:  3
Introduza o passo personalizado:  1


1 2 3 



In [57]:
# EXERCICIO 10

numeros = []
def maior(lista):
    maiorNumero = 0
    for x, y in enumerate(lista):
        if (lista[x] > maiorNumero):
            maiorNumero = lista[x]
    print(f'O maior número é: {maiorNumero}')


qtdNumeros = int(input('Introduza quantos numeros quer introduzir: '))

for x in range(qtdNumeros):
    numero = int(input(f'Introduza o número {x+1}: '))
    numeros.append(numero)

maior(numeros)



Introduza quantos numeros quer introduzir:  3
Introduza o número 1:  1
Introduza o número 2:  3
Introduza o número 3:  2


O maior número é: 3
